<center>
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/images/SN_web_lightmode.png" width="300" alt="cognitiveclass.ai logo">
</center>

<h1 align=center><font size = 5>Assignment: Notebook for Graded Assessment</font></h1>

# Introduction

Using this Python notebook you will:

1.  Understand three Chicago datasets
2.  Load the three datasets into three tables in a SQLIte database
3.  Execute SQL queries to answer assignment questions

## Understand the datasets

To complete the assignment problems in this notebook you will be using three datasets that are available on the city of Chicago's Data Portal:

1.  <a href="https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Socioeconomic Indicators in Chicago</a>
2.  <a href="https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Public Schools</a>
3.  <a href="https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01">Chicago Crime Data</a>

### 1. Socioeconomic Indicators in Chicago

This dataset contains a selection of six socioeconomic indicators of public health significance and a “hardship index,” for each Chicago community area, for the years 2008 – 2012.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2](https://data.cityofchicago.org/Health-Human-Services/Census-Data-Selected-socioeconomic-indicators-in-C/kn9c-c2s2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 2. Chicago Public Schools

This dataset shows all school level performance data used to create CPS School Report Cards for the 2011-2012 school year. This dataset is provided by the city of Chicago's Data Portal.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t](https://data.cityofchicago.org/Education/Chicago-Public-Schools-Progress-Report-Cards-2011-/9xs2-f89t?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### 3. Chicago Crime Data

This dataset reflects reported incidents of crime (with the exception of murders where data exists for each victim) that occurred in the City of Chicago from 2001 to present, minus the most recent seven days.

A detailed description of this dataset and the original dataset can be obtained from the Chicago Data Portal at:

[https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2](https://data.cityofchicago.org/Public-Safety/Crimes-2001-to-present/ijzp-q8t2?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork-20127838&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ)

### Download the datasets

This assignment requires you to have these three tables populated with a subset of the whole datasets.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. 

Use the links below to read the data files using the Pandas library. 

* Chicago Census Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCensusData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Public Schools

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoPublicSchools.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

* Chicago Crime Data

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_Coursera_V5/data/ChicagoCrimeData.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDB0201ENSkillsNetwork20127838-2021-01-01

**NOTE:** Ensure you use the datasets available on the links above instead of directly from the Chicago Data Portal. The versions linked here are subsets of the original datasets and have some of the column names modified to be more database friendly which will make it easier to complete this assignment.

Execute the below code cell to avoid prettytable default error.

In [1]:
!pip install ipython-sql prettytable

import prettytable

prettytable.DEFAULT = 'DEFAULT'

Requirement already satisfied: ipython-sql in c:\users\mgvil\anaconda3\lib\site-packages (0.5.0)
Requirement already satisfied: prettytable in c:\users\mgvil\anaconda3\lib\site-packages (3.16.0)
Requirement already satisfied: ipython in c:\users\mgvil\anaconda3\lib\site-packages (from ipython-sql) (8.20.0)
Requirement already satisfied: sqlalchemy>=2.0 in c:\users\mgvil\anaconda3\lib\site-packages (from ipython-sql) (2.0.25)
Requirement already satisfied: sqlparse in c:\users\mgvil\anaconda3\lib\site-packages (from ipython-sql) (0.5.3)
Requirement already satisfied: six in c:\users\mgvil\anaconda3\lib\site-packages (from ipython-sql) (1.16.0)
Requirement already satisfied: ipython-genutils in c:\users\mgvil\anaconda3\lib\site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in c:\users\mgvil\anaconda3\lib\site-packages (from prettytable) (0.2.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\mgvil\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\mgvil\anaconda3\lib\site-packages (from sqlalchemy>=2.0->ipython-sql) (3.0.1)
Requirement already satisfied: decorator in c:\users\mgvil\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\mgvil\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.18.1)
Requirement already satisfied: matplotlib-inline in c:\users\mgvil\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\users\mgvil\anaconda3\lib\site-packages (from ipython->ipython-sql) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\users\mgvil\anaconda3\lib\site-packages (from ipython->ipython-sql) (2.15.1)
Requirement already satisfied: stack-data in c:\users\mgvil\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.2.0)
Requirement already satisfied: traitlets>=5 in c:\users\mgvil\anaconda3\lib\site-packages (from ipython->ipython-sql) (5.7.1)
Requirement already satisfied: colorama in c:\users\mgvil\anaconda3\lib\site-packages (from ipython->ipython-sql) (0.4.6)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\mgvil\anaconda3\lib\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: executing in c:\users\mgvil\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.8.3)
Requirement already satisfied: asttokens in c:\users\mgvil\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (2.0.5)
Requirement already satisfied: pure-eval in c:\users\mgvil\anaconda3\lib\site-packages (from stack-data->ipython->ipython-sql) (0.2.2)

### Store the datasets in database tables

To analyze the data using SQL, it first needs to be loaded into SQLite DB.
We will create three tables in as under:

1.  **CENSUS_DATA**
2.  **CHICAGO_PUBLIC_SCHOOLS**
3.  **CHICAGO_CRIME_DATA**

Load the `pandas` and `sqlite3` libraries and establish a connection to `FinalDB.db`

In [3]:
# Load required libraries
import sqlite3
import pandas as pd

Load the SQL magic module

In [5]:
# Load IPython SQL extension
%load_ext sql

# Connect to SQLite database (creates the file if it doesn't exist)
%sql sqlite:///FinalDB.db

Use `Pandas` to load the data available in the links above to dataframes. Use these dataframes to load data on to the database `FinalDB.db` as required tables.

In [75]:
census_df = pd.read_csv('C:/Users/mgvil/Desktop/Estudo/Python/ChicagoCensusData.csv')
schools_df = pd.read_csv('C:/Users/mgvil/Desktop/Estudo/Python/ChicagoPublicSchools.csv')
crime_df = pd.read_csv('C:/Users/mgvil/Desktop/Estudo/Python/ChicagoCrimeData.csv')

Establish a connection between SQL magic module and the database `FinalDB.db`

In [81]:
conn = sqlite3.connect('C:/Users/mgvil/Desktop/Estudo/Python/FinalDB.db')
cursor = conn.cursor()

# Write the DataFrames to the database as tables.  chunksize is added to handle large dataframes.
census_df.to_sql('CENSUS_DATA', conn, if_exists='replace', index=False, chunksize=10000)
schools_df.to_sql('CHICAGO_PUBLIC_SCHOOLS', conn, if_exists='replace', index=False, chunksize=10000)
crime_df.to_sql('CHICAGO_CRIME_DATA', conn, if_exists='replace', index=False, chunksize=10000)

# Commit the changes and close the connection
conn.commit()
conn.close()

You can now proceed to the the following questions. Please note that a graded assignment will follow this lab and there will be a question on each of the problems stated below. It can be from the answer you received or the code you write for this problem. Therefore, please keep a note of both your codes as well as the response you generate.

## Problems

Now write and execute SQL queries to solve assignment problems

### Problem 1

##### Find the total number of crimes recorded in the CRIME table.

In [83]:
%sql SELECT COUNT(*) AS total_crimes FROM CHICAGO_CRIME_DATA;

 * sqlite:///FinalDB.db
Done.

[(533,)]

### Problem 2

##### List community area names and numbers with per capita income less than 11000.

In [89]:
%%sql 
SELECT COMMUNITY_AREA_NUMBER, COMMUNITY_AREA_NAME, PER_CAPITA_INCOME
FROM CENSUS_DATA
WHERE PER_CAPITA_INCOME < 11000;

 * sqlite:///FinalDB.db
Done.

[(26.0, 'West Garfield Park', 10934),
 (30.0, 'South Lawndale', 10402),
 (37.0, 'Fuller Park', 10432),
 (54.0, 'Riverdale', 8201)]

In [87]:
%sql PRAGMA table_info(CENSUS_DATA);

 * sqlite:///FinalDB.db
Done.

[(0, 'COMMUNITY_AREA_NUMBER', 'REAL', 0, None, 0),
 (1, 'COMMUNITY_AREA_NAME', 'TEXT', 0, None, 0),
 (2, 'PERCENT_OF_HOUSING_CROWDED', 'REAL', 0, None, 0),
 (3, 'PERCENT_HOUSEHOLDS_BELOW_POVERTY', 'REAL', 0, None, 0),
 (4, 'PERCENT_AGED_16__UNEMPLOYED', 'REAL', 0, None, 0),
 (5, 'PERCENT_AGED_25__WITHOUT_HIGH_SCHOOL_DIPLOMA', 'REAL', 0, None, 0),
 (6, 'PERCENT_AGED_UNDER_18_OR_OVER_64', 'REAL', 0, None, 0),
 (7, 'PER_CAPITA_INCOME', 'INTEGER', 0, None, 0),
 (8, 'HARDSHIP_INDEX', 'REAL', 0, None, 0)]

### Problem 3

##### List all case numbers for crimes involving minors?(children are not considered minors for the purposes of crime analysis)

In [99]:
%%sql
SELECT CASE_NUMBER
FROM CHICAGO_CRIME_DATA
WHERE DESCRIPTION NOT LIKE '%MINOR%';

 * sqlite:///FinalDB.db
Done.

[('HK587712',),
 ('HK456306',),
 ('HT233595',),
 ('HT133522',),
 ('HZ138551',),
 ('HS540106',),
 ('HZ534771',),
 ('HL793243',),
 ('HL149610',),
 ('HK361551',),
 ('HX552797',),
 ('HT180228',),
 ('HV243612',),
 ('HN200365',),
 ('HK108680',),
 ('HY396729',),
 ('HR271603',),
 ('HX332132',),
 ('HW303994',),
 ('HS569246',),
 ('HY234744',),
 ('HP320451',),
 ('HN484464',),
 ('JB151690',),
 ('HR582990',),
 ('HR535632',),
 ('HH486939',),
 ('HW441620',),
 ('HJ561433',),
 ('HR583513',),
 ('HX509438',),
 ('HS681158',),
 ('HK350670',),
 ('G256545',),
 ('JA272438',),
 ('HH201585',),
 ('G212935',),
 ('HL590300',),
 ('HL409680',),
 ('HM324025',),
 ('G662598',),
 ('HV353560',),
 ('HR261581',),
 ('HL680775',),
 ('HM543491',),
 ('HY167451',),
 ('HY377901',),
 ('HX225704',),
 ('HJ308632',),
 ('HV528008',),
 ('HK801112',),
 ('HS532107',),
 ('JA261898',),
 ('JA559176',),
 ('JA412895',),
 ('HY273740',),
 ('HZ224258',),
 ('HJ652747',),
 ('G040244',),
 ('HJ415128',),
 ('HV534721',),
 ('JA503725',),
 ('HM803061',),
 ('HN731220',),
 ('HP691879',),
 ('HV537004',),
 ('HR149903',),
 ('HX314361',),
 ('HV345270',),
 ('HS308747',),
 ('HK728309',),
 ('HL005270',),
 ('HY291329',),
 ('HJ678713',),
 ('HY412959',),
 ('HX155070',),
 ('HV402967',),
 ('HX332979',),
 ('HJ710634',),
 ('HX165034',),
 ('HR385117',),
 ('HS230912',),
 ('HL177398',),
 ('HH702524',),
 ('JA384163',),
 ('HJ672058',),
 ('HT368471',),
 ('HY202462',),
 ('HX354359',),
 ('HZ146741',),
 ('G376790',),
 ('HX262353',),
 ('HP317516',),
 ('HZ335434',),
 ('HS678732',),
 ('HL382289',),
 ('HM392612',),
 ('HH869886',),
 ('HR460350',),
 ('HM117889',),
 ('HR576816',),
 ('HZ372381',),
 ('HZ556726',),
 ('HN421595',),
 ('HK454598',),
 ('HH657809',),
 ('HS451246',),
 ('HH316735',),
 ('G597730',),
 ('G736811',),
 ('HT651635',),
 ('HZ432273',),
 ('G517474',),
 ('HP746347',),
 ('G056330',),
 ('HN772519',),
 ('HZ309936',),
 ('HY368284',),
 ('HL353697',),
 ('HT375934',),
 ('JA188596',),
 ('HL725506',),
 ('HV395700',),
 ('HH696901',),
 ('HT390647',),
 ('HK815196',),
 ('JA490957',),
 ('HK103473',),
 ('HM556695',),
 ('HH558381',),
 ('HK498590',),
 ('HX455839',),
 ('HR703960',),
 ('HL646682',),
 ('HV445580',),
 ('G688026',),
 ('HJ466766',),
 ('HL632721',),
 ('HP579910',),
 ('HL718742',),
 ('HP714065',),
 ('HP716225',),
 ('HW481295',),
 ('HS568476',),
 ('JB213238',),
 ('HS475732',),
 ('HS595785',),
 ('HR408597',),
 ('HT542713',),
 ('HL240985',),
 ('HJ254782',),
 ('HK561262',),
 ('HW213573',),
 ('G419948',),
 ('HL177008',),
 ('HJ639869',),
 ('HM217017',),
 ('HL388623',),
 ('HY189363',),
 ('HS498285',),
 ('HN224900',),
 ('HR387668',),
 ('HJ294892',),
 ('HL745027',),
 ('G533278',),
 ('HH827769',),
 ('HH639427',),
 ('HK771992',),
 ('HH867007',),
 ('HJ575773',),
 ('HR136920',),
 ('HT457930',),
 ('G070193',),
 ('HJ724585',),
 ('HP121474',),
 ('G198370',),
 ('HJ723825',),
 ('HJ458342',),
 ('HP558812',),
 ('HY192694',),
 ('HN472326',),
 ('HK756778',),
 ('HH741961',),
 ('JA460432',),
 ('G140454',),
 ('HX239866',),
 ('HM378171',),
 ('HW182288',),
 ('HZ295843',),
 ('HM673431',),
 ('HP352546',),
 ('HR286405',),
 ('HR195987',),
 ('HW261668',),
 ('JA496716',),
 ('JA344492',),
 ('HZ334220',),
 ('HR217367',),
 ('HV268964',),
 ('JA483294',),
 ('HT169840',),
 ('HT621306',),
 ('HS269736',),
 ('HK243330',),
 ('HH262924',),
 ('HL613433',),
 ('HY267896',),
 ('HN568531',),
 ('HT112422',),
 ('HV479133',),
 ('HV592346',),
 ('HH619797',),
 ('HZ376709',),
 ('HV573337',),
 ('HL269210',),
 ('HL567458',),
 ('HR674429',),
 ('HM200888',),
 ('HX467661',),
 ('HX448587',),
 ('HS200939',),
 ('HN335611',),
 ('HZ535494',),
 ('HX154767',),
 ('HM337445',),
 ('HM244120',),
 ('HR342598',),
 ('HL187666',),
 ('HW449676',),
 ('HS589302',),
 ('HX145326',),
 ('HN553354',),
 ('HN784049',),
 ('HJ527694',),
 ('HM303461',),
 ('HM535632',),
 ('HT353855',),
 ('G134016',),
 ('HR125162',),
 ('G496261',),
 ('HJ842548',),
 ('HN280980',),
 ('JA560123',),
 ('HY405637',),
 ('HP689703',),
 ('HR345366',),
 ('HZ242802',),
 ('HM661326',),
 ('HJ336995',),
 ('HK694552',),
 ('HJ760939',),
 ('HV366181',),
 ('HJ563089',),
 ('HH576932',),
 ('HR308948',),
 ('HK100758',),
 ('HV328581',),
 ('HV267193',),
 ('HJ620738',),
 ('HJ557529',),
 ('HS498920',),
 ('HL608698',),
 ('G323273',),
 ('HK577020',),
 ('HY365876',),
 ('HS305355',),
 ('HK162357',),
 ('HN778969',),
 ('HV185969',),
 ('HH657604',),
 ('HW555338',),
 ('HV268708',),
 ('G170513',),
 ('HW160463',),
 ('HN355411',),
 ('HK190723',),
 ('HV457847',),
 ('HW566855',),
 ('HL141298',),
 ('HR281750',),
 ('HL342355',),
 ('HX112183',),
 ('HJ624999',),
 ('HJ618818',),
 ('HR597126',),
 ('HN558484',),
 ('HR505781',),
 ('HN522324',),
 ('HN647052',),
 ('HT323138',),
 ('HW562748',),
 ('HN719188',),
 ('HT237921',),
 ('HY215032',),
 ('HK369511',),
 ('HL703172',),
 ('HM762800',),
 ('HN370211',),
 ('HR195962',),
 ('HM284854',),
 ('HL319228',),
 ('HR447925',),
 ('HM590293',),
 ('HP513177',),
 ('HL331611',),
 ('HN448271',),
 ('HH402660',),
 ('HN422493',),
 ('HP263901',),
 ('G577663',),
 ('HT535175',),
 ('JA110097',),
 ('HM360756',),
 ('HN275969',),
 ('HZ544441',),
 ('HL660560',),
 ('HS164946',),
 ('HR399710',),
 ('HP243837',),
 ('HP157774',),
 ('HP340132',),
 ('HJ388435',),
 ('JA246453',),
 ('HN407116',),
 ('JA107722',),
 ('HJ532105',),
 ('HH729144',),
 ('HY204891',),
 ('HZ228967',),
 ('HY385205',),
 ('HK328402',),
 ('JA349450',),
 ('HK743113',),
 ('HR185873',),
 ('HH692211',),
 ('JA470839',),
 ('HY182950',),
 ('HR668156',),
 ('HZ234518',),
 ('HW569852',),
 ('HS314108',),
 ('HH463517',),
 ('HN182437',),
 ('HW493063',),
 ('HJ637197',),
 ('HH829588',),
 ('HZ322965',),
 ('HW415978',),
 ('HL315870',),
 ('HJ222529',),
 ('HM535930',),
 ('HZ242203',),
 ('HN213069',),
 ('HH343366',),
 ('JA269772',),
 ('HH106347',),
 ('HM507529',),
 ('HP258815',),
 ('HL111533',),
 ('HS479338',),
 ('HZ403432',),
 ('HV462975',),
 ('HW414519',),
 ('HL414306',),
 ('HT315369',),
 ('HL330223',),
 ('HK751265',),
 ('HT540548',),
 ('HX398190',),
 ('HK348713',),
 ('HR206683',),
 ('HH154448',),
 ('JA462321',),
 ('HV233824',),
 ('HR307075',),
 ('HZ134318',),
 ('HM437597',),
 ('HW233866',),
 ('G659211',),
 ('HW274134',),
 ('HW526270',),
 ('G375927',),
 ('HP325677',),
 ('HL300450',),
 ('HN246122',),
 ('HH149573',),
 ('HK450946',),
 ('HT434553',),
 ('HL548996',),
 ('HR696852',),
 ('HK481967',),
 ('HT202584',),
 ('HJ409442',),
 ('HT251336',),
 ('HV575905',),
 ('HR489129',),
 ('HT427568',),
 ('HR539548',),
 ('HS426544',),
 ('HT556032',),
 ('HL254965',),
 ('JA216127',),
 ('HW350078',),
 ('HR308245',),
 ('HY455377',),
 ('HP747058',),
 ('HN645348',),
 ('HL334216',),
 ('HS230740',),
 ('HV593288',),
 ('HK341632',),
 ('HH859922',),
 ('G611731',),
 ('HM757133',),
 ('HJ786817',),
 ('HV356669',),
 ('HX207970',),
 ('HM733422',),
 ('HH352862',),
 ('G652158',),
 ('HX301095',),
 ('HY163644',),
 ('HR140766',),
 ('HH605275',),
 ('HJ513676',),
 ('HH337319',),
 ('HH423186',),
 ('HN543219',),
 ('HZ463811',),
 ('HN702776',),
 ('HR607189',),
 ('G654957',),
 ('HL131736',),
 ('HN519755',),
 ('G629024',),
 ('HL239939',),
 ('HK328522',),
 ('HJ349966',),
 ('G345035',),
 ('JA394755',),
 ('HY518743',),
 ('JA550741',),
 ('HH493814',),
 ('HZ523997',),
 ('G161722',),
 ('HY455698',),
 ('HH208082',),
 ('HT404945',),
 ('HL213843',),
 ('HM422467',),
 ('JA192460',),
 ('HL446401',),
 ('HS330202',),
 ('HP661088',),
 ('HJ281736',),
 ('HN136243',),
 ('HJ580490',),
 ('HV213648',),
 ('HV514287',),
 ('HJ753917',),
 ('JA133264',),
 ('HJ642080',),
 ('JA557966',),
 ('HV548880',),
 ('HR480844',),
 ('HW568748',),
 ('HH405177',),
 ('HL472862',),
 ('G326063',),
 ('HL424420',),
 ('JA393243',),
 ('HR585012',),
 ('JA455629',),
 ('HV369974',),
 ('HN637742',),
 ('HW557360',),
 ('HJ776916',),
 ('HJ419340',),
 ('HH329720',),
 ('HM802052',),
 ('HJ804627',),
 ('HR190881',),
 ('G575031',),
 ('G122095',),
 ('HN595319',),
 ('G302291',),
 ('G057394',),
 ('HM590468',),
 ('HV463112',),
 ('HK749575',),
 ('HS100098',),
 ('HW576249',),
 ('HK485601',),
 ('HH460583',),
 ('HM576559',),
 ('HL611297',),
 ('HV356389',),
 ('HX203242',),
 ('HH292682',),
 ('G635735',),
 ('HN567387',),
 ('HR391350',),
 ('HM768251',),
 ('HT394616',),
 ('HH688935',),
 ('HK677648',),
 ('G158614',),
 ('HK310265',),
 ('HR314298',),
 ('HT404326',),
 ('HY259084',),
 ('HL415544',),
 ('HP265256',),
 ('HR392537',),
 ('HX343113',),
 ('HM195342',),
 ('HW519443',),
 ('JA359626',),
 ('HN144152',),
 ('HN544458',),
 ('HW238778',),
 ('JB155558',),
 ('HY458571',),
 ('HZ378869',),
 ('HZ378355',),
 ('HX258445',),
 ('HZ192829',),
 ('HZ133234',),
 ('HJ747227',),
 ('JA143710',),
 ('G021609',)]

### Problem 4

##### List all kidnapping crimes involving a child?

In [101]:
%%sql
SELECT CASE_NUMBER, PRIMARY_TYPE, DESCRIPTION
FROM CHICAGO_CRIME_DATA
WHERE PRIMARY_TYPE = 'KIDNAPPING'
  AND DESCRIPTION LIKE '%CHILD%';

 * sqlite:///FinalDB.db
Done.

[('HN144152', 'KIDNAPPING', 'CHILD ABDUCTION/STRANGER')]

### Problem 5

##### List the kind of crimes that were recorded at schools. (No repetitions)

In [103]:
%%sql
SELECT DISTINCT PRIMARY_TYPE
FROM CHICAGO_CRIME_DATA
WHERE LOCATION_DESCRIPTION LIKE '%SCHOOL%';

 * sqlite:///FinalDB.db
Done.

[('BATTERY',),
 ('CRIMINAL DAMAGE',),
 ('NARCOTICS',),
 ('ASSAULT',),
 ('CRIMINAL TRESPASS',),
 ('PUBLIC PEACE VIOLATION',)]

### Problem 6

##### List the type of schools along with the average safety score for each type.

In [107]:
%%sql
SELECT "Elementary, Middle, or High School", 
       AVG(SAFETY_SCORE) AS Average_Safety_Score
FROM CHICAGO_PUBLIC_SCHOOLS
GROUP BY "Elementary, Middle, or High School";

 * sqlite:///FinalDB.db
Done.

[('ES', 49.52038369304557), ('HS', 49.62352941176471), ('MS', 48.0)]

### Problem 7

##### List 5 community areas with highest % of households below poverty line

In [109]:
%%sql
SELECT COMMUNITY_AREA_NAME, PERCENT_HOUSEHOLDS_BELOW_POVERTY
FROM CENSUS_DATA
ORDER BY PERCENT_HOUSEHOLDS_BELOW_POVERTY DESC
LIMIT 5;

 * sqlite:///FinalDB.db
Done.

[('Riverdale', 56.5),
 ('Fuller Park', 51.2),
 ('Englewood', 46.6),
 ('North Lawndale', 43.1),
 ('East Garfield Park', 42.4)]

### Problem 8

##### Which community area is most crime prone? Display the coumminty area number only.

In [111]:
%%sql
SELECT COMMUNITY_AREA_NUMBER
FROM CHICAGO_CRIME_DATA
GROUP BY COMMUNITY_AREA_NUMBER
ORDER BY COUNT(*) DESC
LIMIT 1;

 * sqlite:///FinalDB.db
Done.

[(25.0,)]

### Problem 9

##### Use a sub-query to find the name of the community area with highest hardship index

In [113]:
%%sql
SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE HARDSHIP_INDEX = (
    SELECT MAX(HARDSHIP_INDEX)
    FROM CENSUS_DATA
);

 * sqlite:///FinalDB.db
Done.

[('Riverdale',)]

### Problem 10

##### Use a sub-query to determine the Community Area Name with most number of crimes?

In [115]:
%%sql
SELECT COMMUNITY_AREA_NAME
FROM CENSUS_DATA
WHERE COMMUNITY_AREA_NUMBER = (
    SELECT COMMUNITY_AREA_NUMBER
    FROM CHICAGO_CRIME_DATA
    GROUP BY COMMUNITY_AREA_NUMBER
    ORDER BY COUNT(*) DESC
    LIMIT 1
);

 * sqlite:///FinalDB.db
Done.

[('Austin',)]

## Author(s)

<h4> Hima Vasudevan </h4>
<h4> Rav Ahuja </h4>
<h4> Ramesh Sannreddy </h4>

## Contribtuor(s)

<h4> Malika Singla </h4>
<h4>Abhishek Gagneja</h4>
<!--
## Change log

| Date       | Version | Changed by        | Change Description                             |
| ---------- | ------- | ----------------- | ---------------------------------------------- |
|2023-10-18  | 2.6     | Abhishek Gagneja  | Modified instruction set |
| 2022-03-04 | 2.5     | Lakshmi Holla     | Changed markdown.                   |
| 2021-05-19 | 2.4     | Lakshmi Holla     | Updated the question                           |
| 2021-04-30 | 2.3     | Malika Singla     | Updated the libraries                          |
| 2021-01-15 | 2.2     | Rav Ahuja         | Removed problem 11 and fixed changelog         |
| 2020-11-25 | 2.1     | Ramesh Sannareddy | Updated the problem statements, and datasets   |
| 2020-09-05 | 2.0     | Malika Singla     | Moved lab to course repo in GitLab             |
| 2018-07-18 | 1.0     | Rav Ahuja         | Several updates including loading instructions |
| 2018-05-04 | 0.1     | Hima Vasudevan    | Created initial version                        |
-->
## <h3 align="center"> © IBM Corporation 2023. All rights reserved. <h3/>